### PR TITLE
ensure code is not full width and can be scrolled

### PR DESCRIPTION
**Pull request by r3dDoX**

### CODE REVIEW

**Review by romanutti — APPROVED** [review]

**Comment by r3dDoX** [comment]
Bildschirmfoto 2022-09-06 um 12 54 51

**Comment by romanutti** [comment]
> Bildschirmfoto 2022-09-06 um 12 54 51

Looks great, thanks!

**Review by romanutti — APPROVED** [review]

**Comment by r3dDoX** [comment]
I also gave this theme to one of our designers so maybe we get slight changes in the future but we can adapt to them later on. Shall we merge this PR?

**Comment by romanutti** [comment]
> I also gave this theme to one of our designers so maybe we get slight changes in the future but we can adapt to them later on. Shall we merge this PR?

You can merge it - just saw one thing: It should be merged into feature/new-slidedeck instead of main.

**Pull request merged**
